### ISSUE TITLE
Problem setting file path

### ISSUE THREAD

**Issue by sottwell** [sepiariver/cssSweet#6]
Leaving the path property blank in the plugin property and setting the System Setting to a custom path doesn't work as expected. It says "csss.custom_css_path was not defined. Path set to /paas/cXXXX/www/assets/components/csssweet/" and saves the file there, rather than falling back to the System Setting.

The System Setting is easy enough to set using {assets_path}, but the plugin property needs the whole path. Certainly doable, but a little awkward. Which is why it seemed like it would be nice if it simply defaulted to the System Setting if the plugin property was blank.

**Comment by DESIGNfromWITHIN** [comment]
Can this be fixed in a update? I have this a lot...

**Comment by sepiariver** [comment]
Yes I have a fix for this. Also new version 2.0 will have support for both CSS and JS and use the minification libraries from Google code project. But just need a bit of time. I will likely push a hotfix for this

**Comment by sepiariver** [comment]
Hotfix here: https://github.com/sepiariver/cssSweet/commit/1e12dd1529d41235cf1b35bf900a4f9c3067349a
New package coming... 
System Setting still not being passed as default to `getOption()` in this case—not sure why yet.
@DESIGNfromWITHIN @sottwell
